command:
  - uvicorn
  - app.main:app
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: ''
  - name: DATABRICKS_CATALOG
    value: ''
  - name: LAKEBASE_ENDPOINT_PATH
    value: ''
  - name: LAKEBASE_DATABASE_NAME
    value: ''
